### ISSUE TITLE
Compile error 'Cannot find ctype.h', and link error for libucrt.lib

### ISSUE THREAD

**Issue by sabuncu** [Microsoft/vswhere#119]
I had trouble building vswhere on a Windows 10 Pro (x86) with Visual Studio 2017 Community edition installed (including all related C++ workloads).  The errors:

- Compile error (in both vswhere and vswhere.lib): _'Cannot find ctype.h'_ (when in fact several copies of the file exist on my system)
- Link error (in vswhere): _'Cannot find library libucrt.lib'_

I resolved the compile issue by adding the following folder to `$(AdditionalIncludeDirectories)` to the project properties for both vswhere and vswhere.lib:
`$(ProgramFiles)\Microsoft Visual Studio\2017\Community\SDK\ScopeCppSDK\SDK\include\ucrt`

I resolved the link issue by adding the following folder to `$(AdditionalLibraryDirectories)` to the project properties for vswhere:
`$(ProgramFiles)\Windows Kits\10\Lib\10.0.16299.0\ucrt\x86`

Note: I originally had specified:
`$(ProgramFiles)\Microsoft Visual Studio\2017\Community\SDK\ScopeCppSDK\SDK\lib`
as the location of `libucrt.lib`, but then received a target architecture mismatch error, which makes me think that the `libucrt.lib` copy installed under the `ScopeCppSDK` hierarchy above is incorrect, but that's probably an issue for another component of Visual Studio 2017.

I was able to build and run vswhere on my system.  Hope this helps.

Todd

**Comment by heaths** [comment]
The target CRT is 10.0.14393, as declared in the _vcxproj_ files:
```xml
    <TargetUniversalCRTVersion>10.0.14393.0</TargetUniversalCRTVersion>
```
With that installed, this works right; otherwise, you can retarget to a newer CRT if you want to build your own copy but I have no plans currently to upgrade (no reason to).

**Comment by sabuncu** [comment]
To retarget to a newer CRT, do I simply modify the TargetUniversalCRTVersion in the vcxproj files? Thanks.

**Comment by heaths** [comment]
You could do that, but probably easier to just go to Properties for each project and change the target CRT in the **Configuration Properties --> General** property page, as **Windows SDK Version**. That way the value is validated.

**Comment by sabuncu** [comment]
Thank you, and I am really sorry about opening up a bogus issue.

I did what you suggested, but my Windows SDK Version field shows **7.0** currently, and the only other option available is **8.1**.  If I select 8.1 and click "Apply", the selection does not stick and reverts back to 7.0.  Also, I guess I don't understand the more fundamental issue here, which is, how does the SDK version relate to the version of the folder under the Windows Kits hierarchy.  Thanks again.

![2017-11-16 16_56_51-vswhere lib property pages](https://user-images.githubusercontent.com/6242253/32895044-cc1da054-caef-11e7-99a9-caf8eab2438c.png)

**Comment by heaths** [comment]
Sorry, I do not know. @dangrif do you know?

**Comment by dangrif** [comment]
The <TargetUniversalCRTVersion> property is not exposed via the Visual Studio project properties.  It will need to be modified manually in the project file.

Platform Toolset = *_xp requires the use of the Windows 7.1 SDK. It was the last version of the Windows SDK that supported targeting XP. When the v141_xp Platform Toolset is selected, the only option should be the Windows 7 SDK.

In addition, the Universal CRT is required (which is a subset of the Windows 10 SDK) for any v140* and v141* Platform Toolset.  When the option, below, is selected a subset of the Windows 10 RTM SDK is installed (10.0.10240.0) to satisfy this requirement of the v141* toolsets.

![image](https://user-images.githubusercontent.com/13246303/32916755-dd2edeee-cad1-11e7-9418-a865d68c70c5.png)

However, because vwshere does override the default value for the TargetUniversalCRTVersion property, that version of the Windows 10 SDK is essentially required for a successful build.

**Comment by sabuncu** [comment]
@dangrif, thank you for your thorough explanation.  @heaths, thank you for redirecting the question.

I have a lot of respect for Microsoft.
