### ISSUE TITLE
Access Denied when run under Network Service on Windows 7 SP1

### ISSUE THREAD

**Issue by kulov** [Microsoft/vswhere#147]
I am running VSTS build with Network Service account on Windows 7 Enterprise N SP1.
When I reconfigured my VSTS agent I noticed that MSBuild 15.0 and VS 2017 capabilities are gone.
Digging through the _diag folder I found that powershell add-capabilities is returning Access Denied.

After additional diagnostics I found it is missing access to HKEY_CLASSES_ROOT\Wow6432Node\CLSID\{177F0C4A-1CD3-4DE7-A32C-71DBBB9FA36D}.
I added VSTS Build Service group to have Full Access to the key above (Read access did not work) and vswhere.exe was run successfully. 

So are the build agent capabilities.

**Comment by heaths** [comment]
During registration of the COM server, we merely create keys which inherit their ACL from their parents (e.g. CLSID). This is common with any self-registering COM DLL. It's possible your build servers are locked down more tightly, though I can't say how or why. But either way this is not a problem with vswhere, nor do I suspect any problem with the related COM server DLL for the reason mentioned above. I would take a look at the parent keys' ACLs and adjust as necessary, and compare with a plain installation of Windows. Perhaps this is by design.

**Comment by kulov** [comment]
heaths, thanks for the quick update.

My installation is Windows 7 SP1 with UAC enabled at the time of install. No extra lock downs.

I am not aware of any self-registering COM DLL that vswhere registers. 
Are there any COM servers that vswhere registers? What is the installation procedure for vswhere?
I thought this is a single exe.

I am not aware why this CLSID is needed at all. I just saw vswhere is trying to create COM InProc server from it.
It took me 6+ hours to debug this issue and it is not trivial to troubleshoot at all.

I would suggest to have meaningful error messages instead of general COM Access Denied error.

**Comment by heaths** [comment]
Vswhere doesn't register any COM servers. The Visual Studio installer does that to provide query capabilities to any program.

As discussed previously in other bugs, vswhere is designed to fail gracefully and just not return errors (best effort) but also no instances.I could consider logging detailed event data, but would not change the design since that would be a breaking change.

As for your access decided problem, seems that it's by design the Network Service has limited registry access. See https://msdn.microsoft.com/en-us/library/ff647402.aspx. It's a bit older, but I imagine still applies. And based on https://docs.microsoft.com/en-us/vsts/build-release/concepts/agents/agents?view=vsts#account, running the build agent under the Network Service account may not be ideal for many tasks that require more permissions than that account provides.

**Comment by kulov** [comment]
Better logging should be fine.
It will help pinpoint the problem much faster.

On a side note: I would stick to Network Service for running builds which do not interact with remote resources and do not need interaction with desktop. This is how I am running not very trivial build for many years already. Just as other programs follow the least privilege principle it will be all good and much more secure. For example - vswhere does not need higher privileged account to run I guess.

Thank you!

**Comment by heaths** [comment]
Vswhere and the COM APIs on which it relies needs normal user privileges to just look up COM registration and read files. If Network Services is too restricted for even that, many other VSTS take are likely to fail.

**Comment by heaths** [comment]
Double checking my code, this COM error is one case that should've returned and error code from the process. Did it not?

**Comment by kulov** [comment]
Yes, it did return the general Access Denied error.
It would help quite a lot if it says - Access Denied while accessing interface XXX-XXX... or something similar.
