### ISSUE TITLE
vswhere should support finding specific paths under installation roots

### ISSUE THREAD

**Issue by heaths** [Microsoft/vswhere#162]
We have had a number of requests for vswhere to return paths to specific tools - most often [MSBuild.exe](https://github.com/Microsoft/vswhere/wiki/Find-MSBuild). Because vswhere is a general tool that provides information not only for Visual Studio but Build Tools and other SKUs we install, and because any of those products have unknown numbers of executables or other useful files, locating specific components is not a capability we can accommodate.

At the same time, we realize that making every caller script algorithms like those in our [examples](https://github.com/Microsoft/vswhere/wiki/Examples) puts a burden on all developers when a consolidated algorithm would be easier to use.

We propose a new switch `-find` (like the UNIX find program) that takes a glob pattern as an argument to find executables under the install root. Supported patterns include,

| Token | Description |
| - | -
| * | Find 0 or more of any character.
| ? | Find exactly one of any character.
| ** | In place of a directory token, recursively search for the remaining path.

This is similar to `find` and existing DOS-based globbing support in Windows, with the addition of the globstar (**) that is popular in minimatch patterns.

Used in conjunction with `-latest`, for example, one could easily find MSBuild with whatever directory name they used (it changed between Visual Studio 2017 and 2019):

```powershell
$path = vswhere -latest -requires Microsoft.Component.MSBuild -find "MSBuild\**\Bin\MSBuild.exe"
```

Multiple results are returned in the selected format (`-format value` is the default, like with `-property`) if the pattern matches multiple results, so the more specific you can be the better. A new switch `-sort` will also be added to sort *instances* before returning results - an alternative to `-latest` if you want to find all candidates from newest instance to oldest.

Cc: @refack @KindDragon @3F @uli-weltersbach @IanKemp @zivkan

**Comment by terrajobst** [comment]
Very nice!

**Comment by 3F** [comment]
It really can help to quickly resolve any numbered directories like:

```
VC\Tools\MSVC\14.15.26726\bin\Hostx64\x86\cvtres.exe
```

even to avoid manual checking of arch suffix x86/x32/Win32/ ... you know


**For MSBuild,** it allows to use vswhere simply from command line because `MSBuild\**\` does not require extracting the version anymore.

But, the one note:

* MSBuild tools may require specific workload components for build with it (here's example of errors: https://github.com/3F/hMSBuild/issues/8)

So, what about to add also some logical **OR**, for example, through the same multiple keys to vswhere. 

```
-find "foo" -find "bar" 
```

also for `-requires` key:

```
-requires "Microsoft.Component.MSBuild Microsoft.VisualStudio.Component.VC.Tools.x86.x64" -requires "Microsoft.Component.MSBuild Microsoft.VisualStudio.Component.VC.ATL" 
```

By the way, can we specify multiple `-property` when `-format value` ? 

Although, if the `MSBuild\**\` feature will be finally implemented, it does not matter :) Mainly because of 'installationVersion':

```bat
if /I "%%~a"=="installationPath" set vspath=%%~b
if /I "%%~a"=="installationVersion" set vsver=%%~b
```

**Comment by heaths** [comment]
To make sure we find an instance that you want, the existing switches - like `-requires` and possibly `-requiresAny` (a recent addition) will filter those instances such that a single `-find` should suffice, right?

**Comment by 3F** [comment]
@heaths 

> switches - like -requires and possibly -requiresAny (a recent addition) will filter those instances such that a single -find should suffice, right?

More probably it will be enough to have multiple `-requires` and just a single `-find` key (for the last phase). I'm not sure how does implemented `-requires` in vswhere today, but as the general solution, why not to filter this in order of addition.

> This doesn't provide anything that developers can't do today, but it does mean duplication of effort code

Yes, I noticed :) 

the mentioned hMSBuild uses similar tricks and additional `-vsw-priority` & `-stable` key features.

btw, "MSBuild\ **Current** \Bin" ?

Did I miss something?
https://github.com/3F/hMSBuild/issues/3#issuecomment-322837934

> The VC toolset still presents an interesting challenge if you have multiple versions installed.

exactly :(

But I think, as I said above, we just need to use priority in order of mention for `-requires` keys.
that is, 

```
-requires "Components set #1 we want" -or-> -requires "Components set #2 we want" -or->
```

> For the VC toolset

It was just example, but for some cases (for example, our DllExport tool requires some tool from VC, lib.exe etc) so it may be really uncomfortable to use vsdevcmd.bat and so on.

The other way from wiki `VC\Tools\MSVC\%Version%\bin\HostX64\x64\cl.exe` looks not so pretty for batch scripts because of extracting %Version% (especially set Version=!Version: =!)

so `\**\` really **a lot** :)

**Comment by heaths** [comment]
`-requires` accepts one or more arguments, and technically you should be able to repeat it though 1) that wasn't intentional and may change in the future, and 2) not necessary since you give it multiple arguments. By default, all IDs passed to `-requires` are required (and AND operation). The recently added `-requiresAny` makes it an OR because for a few workloads and components, they have different IDs for the Build Tools SKU.

You definitely should use these prior to relying on `-find` because you first need to find an instance that might possibly have what you're looking for. Imagine if you just did something like this:

```
vswhere -latest -find MSBuild\**\MSBuild.exe
```

The latest instance of VS may not have MSBuild installed, but because `-latest` already limited the results to search, this query would emit no output.

Also, yes, for VS2019 the MSBuild team is changing "{major}.0" to "Current" to make VS2019 and newer easier to automate in devops via vswhere.

**Comment by heaths** [comment]
@refack Yes, installing the VS2019 version of the VS Installer will update vswhere, but if you have a hard dependency on newer features I recommend using the NuGet package regardless of target platform, since .nupkg files are just .zip files you can fetch from a stable URI, unzip, and copy as necessary. This is what most build scripts (including many tasks in Azure Pipelines) do so far as I've discovered or with which I've assisted.

**Comment by heaths** [comment]
We want to put this into the Visual Studio Installer for 16.0 so if anyone who replied here can grab the prerelease and try it out in some of your scenarios that would be great.
