### ISSUE TITLE
Feature Request: Invoke passthrough

### ISSUE THREAD

**Issue by jessehouwing** [Microsoft/vswhere#174]
I'm trying to integrate Visual Studio Diff/Merge with other Git clients. When you know the path to vsdiffmerge.exe that's easy, but in order to make this robust, it's harder.

Tools like Tower support querying the registry for an install path, but don't support the distributed registry files that Visual Studio uses.

Ideally I'd call something like:

```
vswhere -latest -find **\vsdiffmerge.exe -invoke %%args
```

to make it easy to find and invoke the found tool. vswhere would act as a shim for the process being called.

**Comment by heaths** [comment]
You can easily do that in a script. For example, in batch script:

```batch
for /f "usebackq tokens=" in %%i (`vswhere.exe -latest -find **\vsdiffmerge.exe`) do (
  call "%%i" %*
  exit /b %errorlevel%
)
```

As a tool that must remain backward compatible and that I'm trying to keep as small as possible, I'm reluctant to add new features that can easily be layered on top especially when they serve a singular purpose. vswhere is a base tool meant to make locating a compatible Visual Studio (especially 2017 and newer, for which we record the features installed therein) or tools within. Is there some reason the above concept wouldn't work for you?

**Comment by jessehouwing** [comment]
Handling stdin/stdout is my primary concern.

**Comment by heaths** [comment]
How does the above script not allow that? If you're expecting vswhere to also handle all the issues with stdin/stdout that are made in harder in Windows by how the console subsystem fails to deal with them correctly (something that Windows 10 is working to fix, but creates additional complexity), that takes vswhere even further away from the scope for which it was intended. Yet, wrapping it in batch script should actually making dealing with the console subsystem easier since cmd.exe relies on the OS version-specific behaviors already. It will hook up the standard IO handles to any application you call already, so how does the above script still not work for your case?

**Comment by jessehouwing** [comment]
It's my knowledge of all of that which is failing me. It seems.

Other than pure convenience. That script syntax is sooooo darn ugly ;). But
that's outside of your control.

**Comment by heaths** [comment]
Really? I thought it was pretty elegant. PowerShell is even more concise. 😉

At any rate, this should work for your case. vswhere really was meant as a base tool on which to layer needs like this, find compilers or MSBuild for build purposes, and more. Invoking things you find really is outside the scope of this tool, but we can revisit this later if there's enough interest.
