### ISSUE TITLE
MSBuidl 15.0 not found if 16.0 installed

### ISSUE THREAD

**Issue by nsleigh** [Microsoft/vswhere#176]
I have VS2017 build tools installed and have been using "vswhere -version "[15.0,16.0)" -requires Microsoft.Component.MSBuild" without an issue but after installing VS2019 is doesn't find the version 15 tools.

Should this work? 

Specifically I need to find msbuild 15 and would like to use the new "-find" command.

**Comment by nsleigh** [comment]
The solution seems to be to add the "-products *" option e,g, "vswhere -version "[15.0,16.0)" -products * -requires Microsoft.Component.MSBuild"

**Comment by heaths** [comment]
If you were using "%ProgramFiles(x86)%\Microsoft Visual Studio\Installer\vswhere.exe", depending on its version this would make sense, but even `-products` was added a long time ago. We define to actual Visual Studio products. If you want consistency and need a certain set of features, I recommend acquiring vswhere via NuGet (works great for build systems) or Chocolatey (works great for about everything else) rather than require a VS update for the one installed with VS (started shipping in 15.2).

**Comment by nsleigh** [comment]
I am using vswhere from chocolatey.
Visual Studio Locator version 2.6.7+91f4c1d09e [query version 2.0.2250.60958]

**Comment by heaths** [comment]
If the only SKU(s) you had were Build Tools, it never should've returned anything by default without `-products *`. That said, if you had a really old build of Build Tools 2017 installed, it's possible that the query API that vswhere uses (which does ship with the Installer by design) wasn't necessarily compatible with the `-products` switch, but that would mean your Build Tools had to have been older than 15.3, IIRC. Was that the case?

**Comment by nsleigh** [comment]
I am pretty sure it is all up to date, the process I have for keeping the build system updated forces updates to VS and vswhere. VS 2017 build tools is: "Visual Studio Build Tools 2017 - v15.9.7 (VisualStudio/15.9.7+28307.423)".

I have recheck with the latest ("Visual Studio Build Tools 2017 - v15.9.11 (VisualStudio/15.9.11+28307.586)" and it fails in the same way.

**Comment by heaths** [comment]
It's not a bug with vswhere, since it never should've worked. At the very least, there may be a bug in the query API that ships with the Visual Studio Installer but the same scenario is used by Azure Pipelines and appears to be working. What we'd really need is your logs from https://aka.ms/vscollect, which you'd need to attach to a new bug on https://developercommunity.visualstudio.com (contains PII, which you wouldn't want to post here on GitHub; only you and we can see them on DevCom).

**Comment by nsleigh** [comment]
Sorry not sure I am following, which should work?
1. "vswhere -version "[15.0,16.0)" -requires Microsoft.Component.MSBuild"
2. "vswhere -version "[15.0,16.0)" -products * -requires Microsoft.Component.MSBuild"

**Comment by heaths** [comment]
If you had the Build Tools SKU installed, the first command should never have worked. vswhere.exe itself has always defaulted to show only Community, Professional, and Enterprise. The second command is the right, supported command to consider VS and the Build Tools products.

**Comment by nsleigh** [comment]
Many thanks, that was the bit I was missing.
