### ISSUE TITLE
"Find VSTest" wiki page is inconsistent

### ISSUE THREAD

**Issue by IanKemp** [Microsoft/vswhere#179]
The introduction suggests to use:

`vswhere -latest -products * -requires Microsoft.VisualStudio.Workload.ManagedDesktop Microsoft.VisualStudio.Workload.Web -requiresAny -property installationPath`

But the "PowerShell" section suggests:

`vswhere -latest -products * -requires Microsoft.VisualStudio.PackageGroup.TestTools.Core -property installationPath`

Which is more correct?

See also: https://github.com/Microsoft/vswhere/issues/126#issuecomment-363225424

**Comment by heaths** [comment]
Either works, but only workload and component IDs are documented. We try to keep them stable but there are no guarantees since refactoring can and will happen across versions - especially major version releases. Originally, my intent with the wiki was to document the new `-requiresAny` but otherwise leave the examples. Given our level of support for IDs, I have changed them to use `-requiresAny` consistently.
