### ISSUE TITLE
error C2065: 'NBGV_INFORMATIONAL_VERSION': undeclared identifier

### ISSUE THREAD

**Issue by BeErikk** [microsoft/vswhere#183]
`NBGV_INFORMATIONAL_VERSION` is a constant used in 
`vswhere\Program.cpp(156)`

I can't see it defined anywhere in the project, but I suspect you need some build steps to get it created somehow. Please advise.

**Comment by heaths** [comment]
You need to run `nuget restore` on the solution prior to building.

**Comment by BeErikk** [comment]
> nuget restore

OK I ran `nuget` in vswhere git root, like so:
`nuget restore <vswhere>`
I got a prebuilt binary with the message
`"Adding package 'vswhere.1.0.62' to folder 'vswhere\packages'"`

Sorry I'm still a bit lost, where can VS find `NBGV_INFORMATIONAL_VERSION`?

**Comment by heaths** [comment]
In the solution root, just run: `nuget restore`. No arguments. The symbol is generated automatically from one of the packages (Nerdbank.GitVersioning) that gets restored.

**Comment by BeErikk** [comment]
Admin console in git root repository:
F:\dev\vstools\vswhere\vswhere>`nuget restore`
```
MSBuild auto-detection: using msbuild version '4.0' from 'C:\Windows\Microsoft.NET\Framework64\v4.0.30319'.
All packages listed in packages.config are already installed.
```
I guess it should show up in some props file but I can't it.

**Comment by heaths** [comment]
What do you mean you upgraded the packages? All that's necessary is to restore the solution from the solution root directory (the .sln file) and build. Also, if you're using MSBuild 4.0 (which I see from above) it may not support everything. Use a developer command prompt or update your `PATH` to use MSBuild 15.0 from within VS.

**Comment by BeErikk** [comment]
Rightclick solution -> "Restore NuGet packages"
As I said, I did it early on in troubleshooting the failures.

> "and build"
No, the projects need to be retargeted unless I install the VS2017 XP toolset and then some. 

To try again, I did a reset from git to get a clean tree and executed `nuget restore`. I ended up in exactly the same situation. 

It's not difficult to patch the failing parts and get a working binary and a build can be done in many ways. The `NBGV_INFORMATIONAL_VERSION` constant isn't as far as I can tell vital for functionality. I just defined it to 0.

**Comment by heaths** [comment]
A nuget package generates that symbol. I reviewed the change to the project that did it (I also wrote a prototype but someone beat me to merging such a change). But if you're changing the solution and/or project instead of installing the required components, I can't really tell you why it's not working. If you check out the project as-is and restore/build without changes, it should work. It's worked across a myriad of machines with different combinations of VS2017 and VS2019, as well as Azure hosted machines. If there's problems building the unaltered repo with the required components installed, I'm happy to assist further but would need logs.
