### ISSUE TITLE
vswhere didn't detected VS 2010 when only Windows 7.1 SDK are installe.

### ISSUE THREAD

**Issue by lygstate** [microsoft/vswhere#203]

**Comment by heaths** [comment]
Can you clarify? Windows SDK does not install Visual Studio. Are you saying you installed Visual Studio 2010 but only installed Windows SDK? The IDE should have still been installed. Do you see "Visual Studio 2010" in the Start menu?

**Comment by lygstate** [comment]
@heaths, Windows SDK 7.1 Installed Visual Studio 2010 C++ Compiler, Doesn't installed the visual studio IDE, so we can compiling things without the IDE

**Comment by heaths** [comment]
vswhere is for finding Visual Studio, and not individual components installed by VS. Since you know the registry already, you can use that for detection using, for example, reg.exe which ships with Windows instead of this otherwise external dependency. Is there some reason that doesn't work for you?
