### ISSUE TITLE
Specify multiple properties?

### ISSUE THREAD

**Issue by cniggeler** [microsoft/vswhere#207]
Hi, I know I can type vswhere and then search all its output, but I was wondering if it's possible to specify two properties and just have those come out. I tried multiple combinations I could think of but they did not work. For instance, running
vswhere /property installationPath /property instanceID 
just returns the last /property entered: the instance ID.

Thanks!

**Comment by heaths** [comment]
It's not supported, and not really within scope since this is already supported by other means. By the time you need to parse more than one property, you've already done all the work to filter which properties you need, or you're using a format like JSON or XML that you can easily access whichever properties you like.

```batch
@echo off
for /f "usebackq tokens=1* delims=: " %%i in (`vswhere.exe -prerelease -latest`) do (
  if /i "%%i"=="installationPath" (
    set installationPath=%%j
  ) else if /i "%%i"=="instanceId" (
    set instanceId=%%j
  )
)

echo.%installationPath%
echo.%instanceId%
```

Or in PowerShell:

```powershell
$instance = vswhere.exe -prerelease -latest -format json | convertfrom-json
$instance | select installationVersion, instanceId
```

**Comment by cniggeler** [comment]
Got it, thanks!
