### ISSUE TITLE
vswhere from within Activated Environment

### ISSUE THREAD

**Issue by davidbrownell** [microsoft/vswhere#209]
vswhere should leverage environment variables when run from an activated environment.

This change helps when invoking build tools functionality in an xcopy-style-enlistment. xcopy-style-enlistements are helpful to ensure that compiler tool chains are consistent across different environments without resorting to [custom layouts](https://docs.microsoft.com/en-us/visualstudio/install/use-command-line-parameters-to-install-visual-studio?view=vs-2019).

Developer community requests for the ability to install consistently versioned tool chains are available [here](https://developercommunity.visualstudio.com/idea/323050/install-specific-version.html) and [here](https://developercommunity.visualstudio.com/content/idea/353980/please-provide-permanent-deterministic-public-link.html), although these don't quite solve the problem as it still isn't possible to guarantee consistency without a custom layout).

A potential PR that addresses this issue is available at https://github.com/davidbrownell/vswhere/pull/1

**Comment by heaths** [comment]
I appreciate the suggestion, but we don't support pure xcopy-style deployments because not everything in an install is xcopy-able. We do have to install some system components via MSIs or EXEs to support various workloads, and that can only be reliably done through a proper install which will write the necessary information for vswhere to work.

If you want a consistent toolchain, layouts are the supported means. If you want to suggest otherwise, the setup engine has to change first to support it. Please use the Feedback button in the installer to search for existing suggestions or create a new one.
