### ISSUE TITLE
Advise wanted: vswhere output ends with sequence 0xD 0xA (CR LF)

### ISSUE THREAD

**Issue by BeErikk** [microsoft/vswhere#223]
Version of vswhere: Latest `C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe` 2.7.1.3096 2020-06-03.

Inspired from by my effort to enable the MS C++ compiler in WSL, I decided to try to scrap my custom MS compiler batch script which is based on manual version updates and switch to a one that lookup the versions directly from files. A similar example is in vswhere wiki. Like this:
```
set vswhereprog="C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe"
for /f "usebackq tokens=*" %%g in (`%vswhereprog% -latest -property installationPath`) do ( set vsinstalldir="%%g" )
set /p vctoolsversion=<%vsinstalldir%/VC/Auxiliary/Build/Microsoft.VCToolsVersion.default.txt
```
The last line fails because %vsinstalldir% ends with CR LF which mess up the path and the file is not found. So to be able to use the path CR LF needs to be removed. I ended up with:
```
%vswhereprog% -latest -property installationPath | wsl.exe sed 's:\\:/:g' | wsl.exe tr -d '\r\n' > %TEMP%\vspath.tmp
set /p vsinstalldir=<%TEMP%\vspath.tmp
set /p vctoolsversion=<"%vsinstalldir%/VC/Auxiliary/Build/Microsoft.VCToolsVersion.default.txt"
```
So I wonder:
1) Is there a simpler solution?
2) Is there a reason why vswhere ends the output with CRLF?
3) Are you willing to change behaviour?
4) Could vswhere please output the relevant paths to VC tools and Windows SDK as well?

FYI from the WSL .profile file:
```
vswhere='/mnt/c/Program Files (x86)/Microsoft Visual Studio/Installer/vswhere.exe'
vsinstalldir=$(wslpath "$("$vswhere" -latest -property installationPath 2>/dev/null | sed 's:\\:/:g' | tr -d '\r\n')")
vctoolsversion=$(head -n 1 "${vsinstalldir}/VC/Auxiliary/Build/Microsoft.VCToolsVersion.default.txt" | sed -e 's:[[:cntrl:]]::g')
export vctools="$vsinstalldir/VC/Tools/MSVC/$vctoolsversion"
```

**Comment by heaths** [comment]
vswhere uses CRLF in general because it's a Windows application, but it terminates output with CRLF because, if it didn't, some shells (e.g. powershell/pwsh) start their prompt on the same line as the last line of output. What you're doing to strip the last CRLF is a good workaround, but I don't see much value in adding support for this when a workaround is available that would be necessary for many other Windows applications (e.g. wmic.exe).

vswhere is also for finding Visual Studio, not components within its installationPath. The registration system that vswhere uses was never designed to accommodate paths to specific tools; however, the vswhere wiki has examples how to find various common tools including the right VC compilter you want. In the case of VC, there are different compilers for different targets. I added `-find` to make this easier, so as long as you're using a newer vswhere (recommend pulling from nuget, chocolatey, or scoop) you can rely on that. There are examples of that for msbuild as well.
