### ISSUE TITLE
-requires does not find installed component

### ISSUE THREAD

**Issue by giuliov** [microsoft/vswhere#232]
I am installing Visual Studio Build Tools in a Docker container.

If I run `vswhere -version [16.0,17.0) -latest -products *`, it finds the installation, while `vswhere -version [16.0,17.0) -latest -products * -requires Microsoft.VisualStudio.Component.TestTools.BuildTools` is not able to find the test tools.

Event though the Dockerfile explicitly install the component (which is also included in some of the workloads).

```dockerfile
# escape=`
FROM mcr.microsoft.com/dotnet/framework/sdk:4.8-windowsservercore-ltsc2019

WORKDIR C:\\Temp
SHELL ["cmd", "/S", "/C"]

ADD https://aka.ms/vs/16/release/vs_buildtools.exe C:\TEMP\vs_buildtools.exe

RUN vs_buildtools.exe --quiet --wait --norestart --nocache `
    --includeRecommended `
    --add Microsoft.VisualStudio.Workload.ManagedDesktopBuildTools `
    --add Microsoft.VisualStudio.Workload.NetCoreBuildTools `
    --add Microsoft.VisualStudio.Workload.WebBuildTools `
    --add Microsoft.VisualStudio.Workload.MSBuildTools `
    --add Microsoft.VisualStudio.Component.TestTools.BuildTools `
    --add Microsoft.Net.ComponentGroup.TargetingPacks.Common `
    --remove Microsoft.VisualStudio.Component.Windows10SDK.10240 `
    --remove Microsoft.VisualStudio.Component.Windows10SDK.10586 `
    --remove Microsoft.VisualStudio.Component.Windows10SDK.14393 `
    --remove Microsoft.VisualStudio.Component.Windows81SDK `
 || IF "%ERRORLEVEL%"=="3010" EXIT 0

ADD https://github.com/microsoft/vswhere/releases/download/2.8.4/vswhere.exe C:\TEMP\vswhere.exe

ENTRYPOINT ["C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\Common7\\Tools\\VsDevCmd.bat", "&&", "powershell.exe", "-NoLogo", "-ExecutionPolicy", "Bypass"]
```

As you can see I am using the latest vswhere version.

**Comment by heaths** [comment]
>  is not able to find the test tools.

Are you saying that vswhere doesn't find the product, or that it doesn't explicitly find the test tools, which it is not designed to do? That data isn't stored, but we have examples in the wiki how to find them.

**Comment by giuliov** [comment]
The scenario I showed above is the smallest repro I could made after some troubleshooting.

My problem is the VSTest Azure Pipelines Task which uses vswhere to locate `vstest.console.exe` (see screenshot).

![image](https://user-images.githubusercontent.com/1869724/118171442-1ee34d00-b423-11eb-9124-7e72161b1fc0.png)

and I am not able to build an image where that check passes.
Why you say that _it is not designed to do_ when other MS teams rely on it?

**Comment by heaths** [comment]
vswhere doesn't find specific components, which is why I was asking for clarification what you meant when you said it didn't find the test tools.

Did the component install correctly? Connect to the container, copy %PRogramData%\Microsoft\VisualStudio\Packages\_Instances\<instanceId>\state.* (where <instanceId> is the instance ID that vswhere shows), and share it here. Is there only one instance directory under _Instances?

`-requires` indeed works and we have tests for it. The component probably wasn't installed properly. You could also download and run https://aka.ms/collect.exe in the container to collect logs and copy vslogs.zip out of %TEMP% (for the user that ran the install). See https://docs.microsoft.com/en-us/visualstudio/install/advanced-build-tools-container?view=vs-2019#install-script for how I recommend collecting logs if an install fails.

**Comment by giuliov** [comment]
Thanks a lot, this was really helpful.

From the logs I can see **Failed to download** errors, clearly related to some DNS/proxy issue, a frequent source of headaches in our corp environment. 

What puzzles me is why the installer does not return an error code and some packages are correctly installed, masking the root cause.

**Comment by heaths** [comment]
I've found the `||` syntax and using `%ERRORLEVEL%` like that doesn't always work. Not sure if it's docker that has changed over time (they definitely have changed some semantics about how command lines are processed and executed in Windows, though I don't know if it could be related). The link I sent seems to work better - using a separate script. Also, since the installers run in the window subsystem, it might be a good idea to run them through `start /wait` if using cmd.exe as your shell (default for Windows containers) or `start-process -wait` if using PowerShell.

If you copied logs out of the container, I recommend filing an issue at https://developercommunity.visualstudio.com. The setup team can take a look. Perhaps the docs need to be updated if Docker has changed how errors from windows applications are processed.
