### ISSUE TITLE
Unable to get only Visual Studio 2019 installation path

### ISSUE THREAD

**Issue by martin-braun** [microsoft/vswhere#257]
I have VS2019 and VS2022 installed. When I execute

```batch
"%ProgramFiles(x86)%\Microsoft Visual Studio\Installer\vswhere.exe" -nologo -version "16.0" -property installationPath
```

it returns

```
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
C:\Program Files\Microsoft Visual Studio\2022\Community
```

instead of

```
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
```

It also does the same if I use lower versions. Only when using "17.0" I get 2022 only.

**Comment by heaths** [comment]
Because "16.0" is equivalent to "[16.0,)" which means anything equal to or newer then 16.0. If you want to limit to only 16.x, you need to use the range as described in the `-?` help text of vswhere:

```
vswhere -version "[16.0,17.0)" -property installationPath
```

BTW, you don't need `-nologo` if specifying the `-property` parameter, nor for JSON or XML `-format` values.

From `vshwere -?`:

```
  -version arg   A version range for instances to find. Example: [15.0,16.0) will find versions 15.*.
```

More information about the version range - which is the same as for VS extensions (VSIXes) - can be found here: https://github.com/microsoft/vswhere/wiki/Examples.

**Comment by martin-braun** [comment]
@heaths Thanks a lot, now it makes sense to me. The second parameter of the range is exclusive, while the first is inclusive. Your rapid help is much appreciated. :)

**Comment by heaths** [comment]
That's not entirely correct. Square brackets `[` or `]` indicate inclusivity, while parentheses `(` or `)` indicate exclusivity. The wiki link will provide more details.
