### ISSUE TITLE
vswhere does not find visual studio "MsBuildTool" edition

### ISSUE THREAD

**Issue by mucki-at** [microsoft/vswhere#261]
I installed visual studio using this installer: https://aka.ms/vs/16/release/vs_BuildTools.exe and while the resulting installation is fine and works, the included vswhere.exe does not find it. This leads to build problems when building tools in the cloud where build machines would use this edition instead of the more regular enterprise, .... versions.

**Comment by artl93** [comment]
Does VSWhere support build tools? I thought it did…

Art Leonard (he/him)

From: mucki-at ***@***.***>
Date: Monday, March 14, 2022 at 3:44 PM
To: microsoft/vswhere ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [microsoft/vswhere] vswhere does not find visual studio "MsBuildTool" edition (Issue #261)

I installed visual studio using this installer: https://aka.ms/vs/16/release/vs_BuildTools.exe<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Faka.ms%2Fvs%2F16%2Frelease%2Fvs_BuildTools.exe&data=04%7C01%7Cartl%40microsoft.com%7Cc1511a0ccf574dee465508da060c1023%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637828946605282819%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=lof0p3hfQZynTeBYkxKSbqmNbCkccKoCe3BEvqV7Z88%3D&reserved=0> and while the resulting installation is fine and works, the included vswhere.exe does not find it. This leads to build problems when building tools in the cloud where build machines would use this edition instead of the more regular enterprise, .... versions.

—
Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2Fvswhere%2Fissues%2F261&data=04%7C01%7Cartl%40microsoft.com%7Cc1511a0ccf574dee465508da060c1023%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637828946605282819%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=ty4pbc58u907ag822yNtTzGTgkhbY4eUtPVVgEY%2Bvf8%3D&reserved=0>, or unsubscribe<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FACLGGMZFU5RJDYNAM2ZQEL3U766JFANCNFSM5QW6AIUQ&data=04%7C01%7Cartl%40microsoft.com%7Cc1511a0ccf574dee465508da060c1023%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637828946605282819%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=zC7UIutsHPrMNGtHfTOBIrk%2FiX4uFr2TRnXvCGDJ5gw%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cartl%40microsoft.com%7Cc1511a0ccf574dee465508da060c1023%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637828946605332794%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=x03k13sSo9qlU7ZCIazZp5ilEV38g5HyyD%2Bqq25lXDQ%3D&reserved=0> or Android<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cartl%40microsoft.com%7Cc1511a0ccf574dee465508da060c1023%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637828946605332794%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=MAJ83tHBjw3S0N9%2BNhRRDu6Rx3%2FNwJuXhPEqvf%2FUB6g%3D&reserved=0>.

**Comment by artl93** [comment]
Have you tried this? `vswhere -products *`

https://github.com/microsoft/vswhere/wiki/FAQ#why-doesnt-vswhere-find-visual-studio-build-tools

**Comment by heaths** [comment]
@mucki-at if `-products *` doesn't find Build Tools, please reopen and we'd be happy to troubleshoot further.
