### ISSUE TITLE
vswhere.exe problem

### ISSUE THREAD

**Issue by JessieBna** [microsoft/vswhere#292]
ERROR: Could not parse vswhere.exe output
I already installed vswhere.exe from wiki, but there's problem here and I can't install matplotlib

**Comment by heaths** [comment]
Couldn't parse it in what? What shell are you using? What parameters did you pass? More information is needed.

**Comment by JessieBna** [comment]
![Screenshot (146)](https://github.com/microsoft/vswhere/assets/109958325/09dc49a7-5a4c-44c0-9827-889c8f1b05d6)

**Comment by heaths** [comment]
You should file an issue with contourpy since they are calling vswhere. There is not enough to go on here, and they appear to be calling it incorrectly - likely not passing `-utf8`, but that's only a guess based on what little a screenshot - no logs or command lines - can tell me. If they think they found an issue they should open an issue with specifics so we can work out the details.
