### ISSUE TITLE
No output running in Docker

### ISSUE THREAD

**Issue by Linux13524** [microsoft/vswhere#316]
Hi. I'm currently experiencing a strange behavior when running vswhere.exe in a Docker container.

My setup is the following:
* Windows 10 1809
* Docker version 27.1.1
* Docker image based on `dotnet/framework/runtime:4.8-windowsservercore-ltsc2019`
* Visual Studio installed with Chocolatey (`visualstudio2022buildtools` and `visualstudio2022-workload-vctools`)

Running `./vswhere.exe` doesn't output anything, not even the copyright header.
So my guess is that it crashes, but in that case, I'd expect an error output.

Now the bizarre part is that in the **exact** same Docker image on a different Windows host (server 2019) the `./vswhere.exe` works as expected. So it is likely related to the host setup and not the image itself.

The question would be what can cause this? Maybe some missing dependencies on the host? What are the dependencies of vswhere? Can this really affect the vswhere **inside** the Docker container?

I'd be really happy to get some help investigating this :)

**Comment by heaths** [comment]
The image starts? My understanding from the Windows team is that Windows docker images have to be the same or previous (N or N-1) version of the kernel to be supported.

What vswhere command are you running? Formats other than `text` will never print a header.

**Comment by heaths** [comment]
What do you see if you run the `vswhere` command on the Windows 10 host itself?

**Comment by Linux13524** [comment]
I installed `visualstudio2022buildtools` with Chocolatey on the host and `vswhere` seems to work fine:

> PS C:\Program Files (x86)\Microsoft Visual Studio\Installer> .\vswhere.exe
> Visual Studio Locator version 3.1.7+f39851e70f [query version 3.9.2148.60653]
> Copyright (C) Microsoft Corporation. All rights reserved.

**Comment by heaths** [comment]
You'll probably need to run Process Monitor (procmon) in the container and export its log. I've never seen this reported or happen.

**Comment by Linux13524** [comment]
While trying to install `procmon` with Chocolatey in the container I got a step closer: different steps in the installation processes throw errors, one of them being `7z.exe`. It turns out it has the same behavior as `vswhere`, outputting nothing.
Chocolatey gives also the return code for that: **3221225785** (C0000139 in hex).

So next I checked running `vswhere` from Python and got the same error code:

```
>>> import subprocess  
>>> result = subprocess.run("vswhere.exe", stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)  
>>> result.returncode  
3221225785
```

It seems the error code indicates some dependencies are missing. However, it cannot be dependencies **inside** the image as the **exact** same image runs on a different host. 

I continue trying to install `procmon` and maybe something like dependency walker to find out what dependency might be missing.

**Comment by heaths** [comment]
The host kernel is used, so there could actually be missing dependencies. There was a time when Server Core didn't have a font server installed, so some apps wouldn't function correctly. Though that was fixed back then, it could've been regressed (the font server takes up a lot of space), or another system component could missing. Thinking about this more, I remembered righting a bunch of notes and warnings in https://learn.microsoft.com/visualstudio/install/build-tools-container about Server Core not being fully supported by the installer. Too much didn't work. You should use a more expansive edition like Standard. In fact, our system requirements specify Standard or Datacenter already: https://learn.microsoft.com/visualstudio/releases/2022/system-requirements#supported-operating-systems. Core isn't supported, but we don't block on it either because some workloads may work but, again, are not supported. Customers do so at their own risk. This is a case where too much is missing.

Based on https://learn.microsoft.com/dotnet/architecture/microservices/net-core-net-framework-containers/official-net-docker-images#during-development-and-build, to *build* .NET Framework applications you should use the larger SDK images. The runtime images on Server Core are better only to run applications since they have minimal dependencies. To make this easy, the .NET team added multi-stage builds to Docker years ago, as documented here: https://docs.docker.com/build/building/multi-stage/

Hope that helps.
