### ISSUE TITLE
using `-requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64` seem to work for Visual Studio Community but not BuildTools

### ISSUE THREAD

**Issue by LittleCoinCoin** [microsoft/vswhere#320]
Hello,

Components name specifications for C++ for [BuildTools](https://learn.microsoft.com/en-us/visualstudio/install/workload-component-id-vs-build-tools?view=vs-2022) and [Visual Studio Community](https://learn.microsoft.com/en-us/visualstudio/install/workload-component-id-vs-community?view=vs-2022&preserve-view=true) both indicate that component ID `Microsoft.VisualStudio.Component.VC.Tools.x86.x64` is available for install and, therefore, retrieval from `vswhere`.

**Observed Behavior**
1. On a system that used Visual Studio Installer to get _Community_ `MSVC v143 - VS 2022 C++ x64/x86 BuildTools (latest version)`, running the command `.\vswhere.exe -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64` outputs information about the configuration as expected
2. On a system that used Visual Studio Installer to get _BuildTools_ `MSVC v143 - VS 2022 C++ x64/x86 BuildTools (latest version)`, running the command `.\vswhere.exe -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64` DO NOT output anything.

Remark: other components that can be installed both on _Community_ and _BuildTools_ (e.g. windows SDK versions, Cmake tools, and so on) are apparently identical on both systems (i.e. same checkbox names were selected).

**Expected Behaviour**
Case (2) should output the same information as case (1) (given that they use the same version of Visual Studio installer).

**Comment by heaths** [comment]
The product may not have the same component - the same ID, that is. You need to look at the catalog for components and you can pass `-requiresAny` to basically treat the list of `-requires` as an `OR` condition instead of an `AND`. Components may have different IDs if the team that owns them is trying to manage different "views" by composing different components for different products that may have more or fewer binaries in each workload.

You must pass `-product *` to search all products. #130 explains why Build Tools is not included and won't be. It would be breaking behavior. Just add `-product *` if you want to search for all products.
