### ISSUE TITLE
Incorrect PowerShell examples at Find-MSBuild wiki

### ISSUE THREAD

**Issue by nightroman** [Microsoft/vswhere#47]
Examples "Starting with version 1.0.32" and "Starting with version 1.0.40" are
incorrect, they assume that `$path` is the path to `MSBuild.exe` and invoke it
with `$args`. But the actual `$path` is something like

    C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise

So either the returned `$path` is different from expected or this line is missing

````powershell
    $path = Join-Path $path 'MSBuild\15.0\Bin\MSBuild.exe'
````

If it is the latter case, the question is: can we avoid using the hardcoded
sub-path `MSBuild\15.0\Bin\MSBuild.exe` on resolving the `MSBuild.exe` path?

**Comment by heaths** [comment]
I'll correct it, but the `installationPath` is to the VS root. There are many tools under there so you'll always need to use the relative path to whatever tool you need for your scenario. MSBuild is just one example.

**Comment by nightroman** [comment]
Thank you for the explanation. I am just not sure how reliable `MSBuild\15.0\Bin\MSBuild.exe` is. How is it going to work with future versions? What if we use the `latest` installed VS but it is, say, 2018 and the sub-path is `MSBuild\16.0\Bin\MSBuild.exe`? A script with hardcoded `15.0` will be broken.

**Comment by heaths** [comment]
Use the major version of the found instance in place of the "15". I have samples that show that.

The fact is that MSBuild is one of many reasons to find the root of VS. And we don't store each package's root directory because most packages have many directories and install many tools. It's no different than with previous versions of VS when registry was used: find the root and from there find the tool you want within it.

As for 16.0, I can't say what the MSBuild team night do. Seems once they colocated MSBuild under VS they should've removed the version number and maybe they will next time. I can talk with the team and see what we can do to simplify things but given VS has already shipped code would have to support using the major version anyway. One could, instead, append "MSBuild" to the found root and do a recursive search for MSBuild.exe. There's not a lot in the directory so it should be fast.

**Comment by nightroman** [comment]
> It's no different than with previous versions of VS when registry was used: find the root and from there find the tool you want within it.

I must say for MSBuild there was an explicit path provided, e.g. HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\MSBuild\ToolsVersions\14.0 @ MSBuildToolsPath

(Personally, I am interested in MSBuild only, FWIW.)

**Comment by heaths** [comment]
Yes, but that no longer exists because it wouldn't work with instancing, which allows customers to be at different servicing and release levels including MSBuild.

But finding any tool - because everyone's needs are different - under the VS installation root has always meant finding the root installation folder and appending the path to the tool you need for your scenario. For some it's MSBuild. Others may want the path to _devenv.exe_ itself, or to _vstest.console.exe_, or any one of hundreds of tools under the VS installation root.

**Comment by heaths** [comment]
Fixed the wiki.
