### ISSUE TITLE
Synthetic property with path to vcvarsall.bat

### ISSUE THREAD

**Issue by KindDragon** [Microsoft/vswhere#48]
I think it would be useful if you add a synthetic property with a path to vcvarsall.bat.
VS2015 and before: `%installationPath%\VC\vcvarsall.bat`
VS2017 and later: `%installationPath%\VC\Auxiliary\Build\vcvarsall.bat`

**Comment by heaths** [comment]
Thank you for your feedback; however, _vswhere_ is meant for generic use cases - in your case, to get the `installationPath`. Please feel free to use it how you require for your use cases, but there are many that have nothing to do with VC. We simply cannot accommodate every possible need, which is why it returns the root path and the version with which you could make such a determination in script.
