### ISSUE TITLE
Version property doesn't work correctly

### ISSUE THREAD

**Issue by ansterr** [Microsoft/vswhere#50]
Using -version [15.0,16.0) returns an error - Error 0x57: The version "[15.0,16.0)" is not a valid version range.

This error happens on Windows 10 with vswhere 1.0.58, but works correctly on Windows 8.

**Comment by heaths** [comment]
In what shell? Did you try quoting it? Command-line parsing may have changed in Windows 10. I use `CommandLineToArgsvW`. It works fine for me on Windows 10. Make sure you don't have a space after the comma or you will need to quote it. You'll also need to quote it in PowerShell anyway because of both the parenthesis and comma.

**Comment by ansterr** [comment]
I used Windows command line. Tried with and without quotes, no space after the comma .

**Comment by heaths** [comment]
What is the file version of _%ProgramData%\Microsoft\VisualStudio\Setup\x86\Microsoft.VisualStudio.Setup.Configuration.Native.dll_?

**Comment by ansterr** [comment]
1.3.263.2748

**Comment by heaths** [comment]
That's very old. Please install VS2017 RTW which will update those binaries to 1.8.8. That early, I don't believe I had implemented the version range parsing yet (and surprised it isn't erring since I returned `E_NOTIMPL` from the method I use here).

**Comment by ansterr** [comment]
Thanks!
