### ISSUE TITLE
The "-legacy" option does not appear to work with the "-version" option.

### ISSUE THREAD

**Issue by mistachkin** [Microsoft/vswhere#62]
Using the "-legacy" and "-version" options together does not work.  It always outputs all legacy versions.  Either these options should actually work together -OR- using them together should produce an error.

**Comment by heaths** [comment]
`-latest` and `-version` do work together but only if you have VS installed because the parser for the version range is implemented by the COM API that the VS installer installs. `-latest` works by sorting the legacy versions in descending order as seen in https://github.com/Microsoft/vswhere/blob/develop/src/vswhere.lib/InstanceSelector.cpp#L145-L156.

At this time, I have no plans to duplicating the version range parsing logic in _vswhere_ to handle when the COM API is not installed. What scenario are you trying to support that you need to specify a version range with only legacy products installed?

**Comment by mistachkin** [comment]
I was trying to query for only Visual Studio 2015 using "-version 14.0"; instead it returned 2010 to 2015.  Perhaps you could add a small check to see if the COM API is installed and disallowed -version with -legacy *in that case*?
