### ISSUE TITLE
Feature request: return a non-zero exit code when no VS is found

### ISSUE THREAD

**Issue by AustinWise** [Microsoft/vswhere#65]
Currently the program exits with `ERROR_SUCCESS` even if no version of Visual Studio was found. So for example if you are just trying to get the installation path, the calling script has to look for an empty string.

Would there be any objection to changing the return code to an error if no version is found? I can send a pull request.

**Comment by heaths** [comment]
It is by design that it returns success. Many interpreters (not just batch) would err instead of parse output, which may be empty. Consider `vswhere -format json | convertfrom-json` in PowerShell. It's not inherently an error to not have instances. If not having instances is an error in your scripts, you could then return an error.

Even in batch script, you'd still have to check `%ERRORLEVEL%` so checking if a variable that would've captured the result (as many of the examples on this site show) is empty is no worse/better.

**Comment by ElektroStudios** [comment]
That logic explained by @ heaths is completely wrong. The program should be responsible to return an exit-code (0 for success, 1 for fail following standard convention) depending on the results (VS found, VS not found).

vswhere is a console application that could be launched from any language, and the standard is to expect an exit-code from the launched executable, not to check if the stdout is empty... what the hell?.

Exit-codes exists for a good reason, and the author developer MUST BE responsible of adding this basic and needed feature, otherwise it lose much sense to use this application in any scenario because non-exitcode means non-right programming guidelines for the end-user... since you are forcing us to check an empty stdout... it has no sense, really.

Thanks for read.

**Comment by heaths** [comment]
Who says finding no instances is an error? Maybe it's an error in your case, and you can handle empty results however you see fit. No only is this behavior by design based on early feedback, do return a non-zero exit code now would be a breaking change.

**Comment by AustinWise** [comment]
I think for a lot of a use cases a failure to find VS is an error for calling script. It feels mildly redundant to have to both check the error code and output of vswhere.exe in a batch script.

Would you accept a pull request that added a command line flag to exit with an error when no VS is found? That would be backwards compatible and simplify scripts that would like to treat the absence of VS as an error.

**Comment by heaths** [comment]
Depending how it's implemented I would consider it. The minor version would need to be bumped.

**Comment by heaths** [comment]
So answer me this: since you have to capture the output of _vswhere_ (to find installation path or whatever you need) anyway, why is it any more work to check if the result is empty? That's exactly what I do in the various (examples)[https://github.com/Microsoft/vswhere/wiki/Examples].

```batch
@echo off

for /f "usebackq tokens=*" %%i in (`vswhere -latest -products * -requires Microsoft.Component.MSBuild -property installationPath`) do (
  set InstallDir=%%i
)

if exist "%InstallDir%\MSBuild\15.0\Bin\MSBuild.exe" (
  "%InstallDir%\MSBuild\15.0\Bin\MSBuild.exe" %*
)
```
If I did return an exit code, you'd still have to parse the output if you didn't get one. So how does returning an error code actually improve anything?

**Comment by heaths** [comment]
@AustinWise, @ElektroStudios, @leidegre: I'm opening to adding a switch to return an error code (opting in to avoid breaking behavior) - which is why I've reopened this bug for now - but I still need to understand:

1. Why, when you have to capture output anyway to get the string results (since no OS supports returning strings from a process entry point), is returning an exit code instead of empty results any better?
2. In exactly what cases do you want an error? Failure because the query API isn't installed? Failure to find the specific VS if others were found? I don't think the latter is failure case: SQL queries, PowerShell `where` clauses, etc. - no filter matches is simply an empty result set. I could see returning an error if opted in if the query API isn't even installed.

The idea was that errors are only returned for syntax errors so those are discoverable at authoring time. This is geared for script authors (like for build automation) who don't control end users' machines. And since you have to capture output anyway, I don't see how non-syntax error codes improve anything. Please clarify.

**Comment by AustinWise** [comment]
I thought that if the exit code could be relied upon to indicate that a version of VS was found, the `if exists` check could be left out. However, after I got back from vacation I wrote the following test batch script:

```batch
for /f "usebackq tokens=*" %%i in (`cmd.exe /c exit 1`) do (
  set "InstallDir=%%i"
)
echo %ERRORLEVEL%
```

This prints `0`. So even if this feature were added, it would not be possible to actually test the exit code from batch scripts.

I think this feature would still make the PowerShell version a little simpler:
```powershell
$path = vswhere -errorOnNotFound -latest -products * -requires Microsoft.Component.MSBuild -property installationPath
if ($LASTEXITCODE -eq 0) {
  $path = join-path $path 'MSBuild\15.0\Bin\MSBuild.exe'
  & $path $args
}
```

But since the paths of things move around between releases of VS, the tests for path existence probably have to stay around, so this feature would not be very useful.

**Comment by heaths** [comment]
You could just as easily replace the condition with `if ($path)`. My point above was that you have to capture output anyway, and precisely because PowerShell sets `$?` and `$LASTEXITCODE` - which may, depending on `$ErrorActionPreference`, fail a script - that I don't return an exit code. No search results, no results returned to stdout that you have to capture anyway. I see no added benefit to exit codes.

**Comment by AustinWise** [comment]
What I was hoping for was something like bash's `set -e` mode, where errors would stop the script and I could elide exit code checking. Unfortunately, neither batch files nor PowerShell scripts seem to support this (see PowerShell/PowerShell#3415 ).

For example, this program:
```powershell
$ErrorActionPreference = "Stop"
& cmd.exe /c exit 123
echo "Got exit code: $LASTEXITCODE"
```

prints:

```
Got exit code: 123
```

Thus I agree with your assessment that having a non-zero exit code would be of little benefit.
