### ISSUE TITLE
Unable to locate the MSBuild component when only "Build tools for Visual Studio 2017" is installed

### ISSUE THREAD

**Issue by viswaug** [Microsoft/vswhere#68]
I only have the "Build Tools for Visual Studio 2017" installed on our build server. I need to locate the MSBuild.exe file. Running "vswhere" does not return anything back. I also tried running "vswhere -latest -requires Microsoft.Component.MSBuild"

I am missing something here? Is it not supposed to work with the build tools?

**Comment by heaths** [comment]
Please see issue #61. tl;dr: _vs_where finds VS SKUs by default, but does provide an easy way of finding other SKUs with the `-products` parameter.

**Comment by viswaug** [comment]
Thank you. Appreciate it. Also would you know why the "vswhere" command and the "Select-VSSetupInsatnce" cmdlet work fine when i specify "-product *" or "-products *" respectively. But not when i specify the product name to be "BuildTools" like mentioned in the wiki https://github.com/Microsoft/vswhere/wiki/Find-MSBuild

**Comment by heaths** [comment]
Because the ID is "Microsoft.VisualStudio.Product.BuildTools". The sample users something like `%pre%BuildTools`, where `pre` is defined as "Microsoft.VisualStudio.Product.", so it resolves to the same thing.

Only the PowerShell cmdlets support wildcards like "*BuildTools". If someone wants to add CPU-inexpensive support for wildcards to _vswhere_ I'd be happy to look at a PR. I just didn't have the time originally and there's not been a big ask for it since _vswhere_ is more typically used in scripting scenarios where typing a bit longer string once isn't much of an issue. The cmdlets are more exploratory in nature.
