### ISSUE TITLE
Error when calling in batch file

### ISSUE THREAD

**Issue by ygoe** [Microsoft/vswhere#84]
I've created a batch file named vs.cmd with the following content:

```
@echo off

for /f "usebackq tokens=*" %%i in (`"C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" -prerelease -latest -products * -requires Microsoft.Component.MSBuild -property installationPath`) do (
  set InstallDir=%%i
)

if exist "%InstallDir%\MSBuild\15.0\Bin\MSBuild.exe" (
  echo MSBuild installed in: %InstallDir%\MSBuild\15.0\Bin\MSBuild.exe
)
```

(Needed to fix the vswhere.exe path because it's not in the %PATH%.)

Here's the output:

> "\Microsoft" kann syntaktisch an dieser Stelle nicht verarbeitet werden.

So that didn't work. Not sure how this is supposed to work at all because the backtick operator doesn't seem to be supported in Windows CMD. Is this a Bash script actually?

**Comment by heaths** [comment]
If you remove `@echo off`, you'll see the problem is in the `set` expression. Regardless, this would be a problem with batch parsing of the `for` command, which https://stackoverflow.com/questions/6474738/batch-file-for-f-doesnt-work-if-path-has-spaces has recommendations for (though apparently not necessary in newer versions of Windows, as this works as-is on Windows 10 for me using even a full path in the script examples at 
https://github.com/Microsoft/vswhere/wiki/Find-MSBuild#batch).

Given your output is in German, could this be code page issue copying and pasting? If I take my following example and put a full path in there, it works:

```batch
@echo off

for /f "usebackq tokens=*" %%i in (`call "%ProgramFiles(x86)%\Microsoft Visual Studio\Installer\vswhere.exe" -latest -products * -requires Microsoft.Component.MSBuild -property installationPath`) do (
  set InstallDir=%%i
)

if exist "%InstallDir%\MSBuild\15.0\Bin\MSBuild.exe" (
  "%InstallDir%\MSBuild\15.0\Bin\MSBuild.exe" %*
)
```

I retyped the script you pasted above into a batch file (UTF-8 encoded, latin keyboard) and it worked fine when I put `call` before the quoted path.

**Comment by ygoe** [comment]
That thing still fails as before. I guess CMD was never and will never be a predictable scripting language. Also, that thing still uses the magic number "15" to find the actual MSBuild path. That's probably as useless as before. `vswhere` could be useful if it provided the actual MSBuild path and could provide that path directly into an environment variable. But it doesn't provide the first, and the second can only be done with PowerShell or Bash, not CMD.

**Comment by heaths** [comment]
_vswhere_ is not specific to MSBuild nor even VS. You can use it to find whatever programs you need. If those programs have additional requirements to support side-by-side installs, you'll need to account for those requirements. You're welcome to leave feedback on https://developercommunity.visualstudio.com for respective teams to consider.

The script works on several OS versions I've tried. It likely is an issue with your code page. You can use `chcp` to see what the current value is, and there is a page on the wiki that explains how to work with different code pages. Beyond that, Stack Overflow may provide better help dealing with code page issues. If you're copying and pasting, make sure that your editor is not transcoding quotes as smart quotes or any other extended characters. As typed, there should be no expected characters beyond the ASCII plane.

**Comment by ygoe** [comment]
It's certainly not a codepage issue, this script only uses ASCII characters. My codepage is 850 (Western DOS). OS is Windows 7.

**Comment by 3F** [comment]
> ...to find the actual MSBuild path. ... But it doesn't provide the first, and the second can only be done with PowerShell or Bash, not CMD.

@ygoe you should use additional processing/tool for work with msbuild because the `vswhere` does not directly related for this tool. 

We already discussed about this here - #41, so you can also try to use hMSBuild because it's the **only 1 batch file** that's needed.

@heaths I think, could be useful to add some note about this for everyone who just need a msbuild tools.

**Comment by ygoe** [comment]
Wow, it looks like rocket science to actually find that MSBuild.exe, even more with each new version of Visual Studio. Maybe it's just simpler to use `dotnet msbuild` from the .NET CLI?

**Comment by 3F** [comment]
@ygoe it does not require anything else for user environment (you don't need powershell, or dotnet-cli), just 1 batch script that can be embedded inside other batch scripts etc. Thus, this is the most easy way to provide guaranteed access to any available msbuild tools that's needed (from .NET or VS including latest VS2017) with your source code and any cases like from #41 etc. Or what do you mean ?

**Comment by heaths** [comment]
@3F I added an example long ago to find MSBuild. I don't know why it doesn't work for @ygoe because if I copy and paste from my example or type it manually (with full path) it works fine on my machines (even Windows 7), but if I copy and paste from his example it doesn't. I have not checked the hex representation of the code points, but it does not indicate a problem with _vswhere_ so there may be better options for dealing with code page issues regarding batch scripts.

As noted elsewhere, _vswhere_ is and will remain generic. With the exception of "15.0" being in the path - and I have mentioned to the MSBuild team this seems unnecessary and is causing issues with callers - it's a fairly fixed path. You can wrap _vswhere_ with scripts to find any tool you want. That's the point.

**Comment by 3F** [comment]
@heaths

> if I copy and paste from his example it doesn't. 

if you about script from [first post](https://github.com/Microsoft/vswhere/issues/84#issue-242918381)

> Here's the output:
>    "\Microsoft" kann syntaktisch an dieser Stelle nicht verarbeitet werden.


```bat
chcp 437
\Microsoft was unexpected at this time.
```

seems trivial problem with whitespace symbols here:

```bat
echo MSBuild installed in: %InstallDir%\MSBuild\15.0\Bin\MSBuild.exe
```

that is, works for me after this changes:

```bat
echo MSBuild installed in: "%InstallDir%\MSBuild\15.0\Bin\MSBuild.exe"
```
